name: Update

on:
  push:
    branches: [ "main" ]

env:
  REMOTE_HOST: "ec2-52-90-54-79.compute-1.amazonaws.com"
  REMOTE_USER: "ec2-user"

permissions:
  contents: read
  id-token: write

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH set up
        run: |
          mkdir -p ~/.ssh/
          echo "$AWS_SSH" > ~/.ssh/CI-CD-Key
          chmod 600 ~/.ssh/CI-CD-Key
          ssh -i ~/.ssh/CI-CD-Key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST Cadiz_Peiffer_ec2/redeploy
        env:
          SSH_HOST: ${{ env.REMOTE_HOST }}
          SSH_USER: ${{ env.REMOTE_USER }}
          SSH_KEY: ${{ secrets.labsuser.pem }} 
